package hipo.com.customviewexercise;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by Tolga Can "tesleax" Ünal on 13/06/17
 */
@Entity
public class Object {
    @Id
    private long id;
    private String name;
    @Generated(831798629)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Object(long id, String name) {
        this.id = id;
        this.name = name;
    }

    @Override
    public String toString() {
        return id + "-" + name;
    }

    @Generated(681462569)
    public Object() {
    }
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
